POST http://localhost:3000/products
Content-Type: application/json

{
    "title": "tent 3",
    "category": "tools",
    "product_description": "tent",
    "img": "https://i.postimg.cc/QNvytvdS/teepee-tent-camping-equipment-shelter.jpg",
    "quantity": 1
}
###
GET http://localhost:3000/products