POST http://localhost:3000/products
Content-Type: application/json

{
    "title": "tent 2",
    "category": "tools",
    "product_description": "tent",
    "img": "https://i.postimg.cc/5NTsJRHZ/1456740848613240.jpg",
    "quantity": 1
}
###
GET http://localhost:3000/products
