POST http://localhost:3000/products
Content-Type: application/json

{
    "title": "shovel",
    "category": "tools",
    "product_description": "metal shovel",
    "img": "https://i.postimg.cc/dQ6LsjTB/415029-1500.png",
    "price": 800,
    "quantity": 1
}
###
GET http://localhost:3000/products
